### ISSUE TITLE
Error while reading core-site.xml in elasticsearch bootstrap action

### ISSUE THREAD

**Issue by sourabp** [aws-samples/emr-bootstrap-actions#217]
Getting the following error on installing elasticsearch bootstrap action for emr 4.9.5 and elasticsearch 2.3.4:
```
initialize': No such file or directory - /etc/hadoop/conf/core-site.xml (Errno::ENOENT)
	from /emr/instance-controller/lib/bootstrap-actions/1/elasticsearch_start.rb:33:in `new'
	from /emr/instance-controller/lib/bootstrap-actions/1/elasticsearch_start.rb:33:in `load_aws_keys'
	from /emr/instance-controller/lib/bootstrap-actions/1/elasticsearch_start.rb:51:in `install_elasticsearch'
	from /emr/instance-controller/lib/bootstrap-actions/1/elasticsearch_start.rb:100:in `<main>'
```
One possible reason could be that spark/ yar is not installed at the time this action is invoked.
Please confirm if this is the cause and provide resolution for the same.

**Comment by dacort** [comment]
Hi there - thanks for your contribution. We're updating this repository to include more relevant and recent information. 

As such, we're cleaning up and closing old issues and PRs.

Feel free to open an issue if you still use EMR and would like to see an example of something!
